### ISSUE TITLE
go vet generic type error and go test [build failed] on stmutil pkg

### ISSUE THREAD

**Issue by datewu** [anacrolix/stm#5] opened 2022-10-20 14:21 UTC
Very strange,  github ci marks `go vet  ./...  ` and `go test` fails, while i'm pretty sure i change no stm/stmutil pkg dependency.

Then i found out `go build ` works on my machine, but `go vet ./...` and `go test` fails like the github ci:

Both local machine and ci machine's go version are go 1.19.2.
 

```shell
# github.com/anacrolix/stm/stmutil
/Users/r/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:72:3: cannot use generic type immutable.Map[K constraints.Ordered, V any] without instantiation
/Users/r/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:76:9: cannot use Map{…} (value of type Map) as type Mappish in return statement:
        Map does not implement Mappish (missing Get method)
/Users/r/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:76:30: type interhash of interhash{} does not match immutable.Hasher[K] (cannot infer K and V)
/Users/r/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:79:17: cannot use Map{} (value of type Map) as type Mappish in variable declaration:
        Map does not implement Mappish (missing Get method)
/Users/r/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:83:9: cannot use m (variable of type Map) as type Mappish in return statement:
        Map does not implement Mappish (missing Get method)
/Users/r/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:88:9: cannot use m (variable of type Map) as type Mappish in return statement:
        Map does not implement Mappish (missing Get method)
/Users/r/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:107:3: cannot use generic type immutable.SortedMap[K constraints.Ordered, V any] without instantiation
/Users/r/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:112:9: cannot use sm (variable of type SortedMap) as type Mappish in return statement:
        SortedMap does not implement Mappish (missing Get method)
/Users/r/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:117:9: cannot use sm (variable of type SortedMap) as type Mappish in return statement:
        SortedMap does not implement Mappish (missing Get method)
/Users/r/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:182:14: cannot use generic type immutable.List[T comparable] without instantiation
/Users/r/go/pkg/mod/github.com/anacrolix/stm@v0.4.0/stmutil/containers.go:117:9: too many errors
# github.com/anacrolix/dht/v2/k-nearest-nodes
/Users/r/go/pkg/mod/github.com/anacrolix/dht/v2@v2.19.0/k-nearest-nodes/k-nearest-nodes.go.go:21:9: cannot use generic type immutable.SortedMap[K constraints.Ordered, V any] without instantiation
/Users/r/go/pkg/mod/github.com/anacrolix/dht/v2@v2.19.0/k-nearest-nodes/k-nearest-nodes.go.go:29:33: type lessComparer of lessComparer{…} does not match immutable.Comparer[K] (cannot infer K and V)

```

This [github action](https://github.com/datewu/zhongzi/actions/runs/3280686471 ) may provide you more info.

**Comment by anacrolix** [comment] 2022-10-21 08:38
That's very peculiar. I tried a bunch of theories and can't see why. I'm also not able to reproduce. I think I did see this problem early on with go1.19 before it was released.

**Comment by ucwong** [comment] 2022-10-25 23:55
@anacrolix https://github.com/anacrolix/stm/pull/6

**Comment by anacrolix** [comment] 2022-10-26 10:12
Turns out this issue is due to `github.com/benbjohnson/immutable` being upgraded to `v0.4.0`. Did you by any chance do `go get -u` from a downstream project? FWIW, `go get -u` doesn't do what people think it does for the most part, it forces dependencies of your dependencies to be updated, rather than just your immediate dependencies.

**Comment by ucwong** [comment] 2022-10-26 18:31
https://github.com/anacrolix/stm/pull/7 @anacrolix

**Comment by anacrolix** [comment] 2022-10-26 22:38
@ucwong here is an alternate line of fixes, let me know your thoughts: https://github.com/anacrolix/stm/tree/immutable-v0.4.0. Based on the change in constraints on map keys, I'm not sure updating to v0.4.0 is going to be plausible if this is still in use from anacrolix/dht. It certainly doesn't pass one of the tests that uses a set of `*stm.Var`.
```
# github.com/anacrolix/stm_test [github.com/anacrolix/stm.test]
./external_test.go:102:40: *stm.Var[bool] does not implement constraints.Ordered (*stm.Var[bool] missing in ~int | ~int8 | ~int16 | ~int32 | ~int64 | ~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~uintptr | ~float32 | ~float64 | ~string)
```

**Comment by ucwong** [comment] 2022-10-26 22:53
@anacrolix I think update to latest version and  follow the constrains on the Map like var define should be the reasonable way, if we can't abandon immutable dependency right now. And the future Golang version may be also strict in Map like vars defined. Issues about ``` go get -u ./...``` seems not to be very graceful.

**Comment by anacrolix** [comment] 2022-10-26 23:15
I don't quite understand. For now you may find it easiest to progress without updating immutable, until something is figured out.

**Comment by ucwong** [comment] 2022-10-26 23:37
> I don't quite understand. For now you may find it easiest to progress without updating immutable, until something is figured out.

yes, just implement the missing func of interface used. Is this OK for merging https://github.com/anacrolix/stm/pull/7

**Comment by anacrolix** [comment] 2022-10-27 03:28
Are you able to pass all the tests in anacrolix/stm, with immutable v0.4.0, with your changes?

**Comment by ucwong** [comment] 2022-10-27 18:07
> Are you able to pass all the tests in anacrolix/stm, with immutable v0.4.0, with your changes?

https://github.com/benbjohnson/immutable/compare/v0.3.0...v0.4.0
I think it is not necessary to add strict constrains to a collections project like this, it should give more space to the users for convenience. Lock the version at 0.3.0 is enough.

**Comment by anacrolix** [comment] 2022-10-27 22:18
I'm happy to take a PR that updates to v0.3.0 if you like (and ensuring it works with anacrolix/dht). I suspect you may want to undo some of the recent changes you made?

**Comment by ucwong** [comment] 2022-10-28 00:26
@anacrolix  https://github.com/anacrolix/stm/pull/8  revert pre-pr

**Comment by datewu** [comment] 2022-10-28 02:20
> Turns out this issue is due to `github.com/benbjohnson/immutable` being upgraded to `v0.4.0`. Did you by any chance do `go get -u` from a downstream project? FWIW, `go get -u` doesn't do what people think it does for the most part, it forces dependencies of your dependencies to be updated, rather than just your immediate dependencies.

Yes, i do ` go get -u ./...` and i did it a lot. It's in my Makefile 🤣 .  
After using  replace directive `replace github.com/benbjohnson/immutable v0.4.0 => github.com/benbjohnson/immutable v0.3.0` in my go.mod file, things work out. Both `make` and `stmutil` are happy.
Thanks again.

**Comment by anacrolix** [comment] 2022-10-28 03:22
No worries, thanks @datewu. As I mentioned above, `go get -u` is a bit of an anti-pattern, but that's my strong opinion after being burned by it many times.

**Comment by anacrolix** [comment] 2022-12-21 01:04
This should be fixed by https://github.com/anacrolix/stm/commit/32174bfc2d877d4b3df131c9e2c7704a82755443.

**Closed as completed by anacrolix** 2022-12-21 01:04 UTC
